var data = [
  {name: '纳爱斯集团有限公司', person:  '张蕾', seat:  '7排45号'},
  {name: '丽水博远科技有限公司', person:  '罗彬', seat:  '7排46号'},
  {name: '浙江梦马电子商务有限公司', person:  '刘思成', seat:  '7排47号'},
  {name: '丽水网新正合科技服务有限公司', person:  '陈军铭', seat:  '7排48号'},
  {name: '丽水市润生苔藓科技有限公司', person:  '温从发', seat:  '7排49号'},
  {name: '浙江新量象网络科技有限公司', person:  '吴伟伟', seat:  '7排50号'},
  {name: '浙江乾麟缝制设备有限公司', person:  '', seat:  '7排51号'},
  {name: '浙江瑞新药业股份有限公司', person:  '', seat:  '7排52号'},
  {name: '浙江乐谷科技有限公司', person:  '', seat:  '7排53号'},
  {name: '瓯宝安防科技股份有限公司', person:  '', seat:  '7排54号'},
  {name: '浙江航星电机有限公司', person:  '', seat:  '7排55号'},
  {name: '浙江丽水浙邦网络营销有限公司', person:  '', seat:  '7排56号'},
  {name: '恒大电气有限公司', person:  '', seat:  '7排57号'},
  {name: '丽水市鱼跃酿造食品有限公司', person:  '', seat:  '7排58号'},
  {name: '浙江慧和健康科技有限公司', person:  '', seat:  '7排59号'},
  {name: '浙江泓晨农业产业有限公司', person:  '', seat:  '7排60号'},
  {name: '浙江多乐缝纫机有限公司', person:  '', seat:  '7排61号'},
  {name: '浙江特利隆精密机械有限公司', person:  '', seat:  '7排62号'},
  {name: '富来森集团有限公司', person:  '', seat:  '7排63号'},
  {name: '丽水市绿洁食品有限公司', person:  '', seat:  '7排64号'},
  {name: '浙江国镜药业有限公司', person:  '万芬芬', seat:  '7排45号'},
  {name: '浙江三田汽车空调压缩机有限公司', person:  '王凯', seat:  '7排46号'},
  {name: '浙江广力工程机械有限公司', person:  '吴丽红', seat:  '7排47号'},
  {name: '浙江基力思汽车空调有限公司', person:  '陈永辉', seat:  '7排48号'},
  {name: '浙江新劲空调设备有限公司', person:  '范志伟', seat:  '7排49号'},
  {name: '浙江恒祥玩具有限公司', person:  '项伟英', seat:  '7排50号'},
  {name: '浙江毅力汽车空调有限公司', person:  '吴崇建', seat:  '7排51号'},
  {name: '浙江能福旅游用品有限公司', person:  '刘菊芝', seat:  '7排52号'},
  {name: '浙江创新汽车空调有限公司', person:  '孙飞', seat:  '7排53号'},
  {name: '龙泉市御品瓷坊', person:  '季总', seat:  '7排54号'},
  {name: '浙江渊健生物药业有限公司', person:  '周鹏程', seat:  '7排55号'},
  {name: '起步股份有限公司', person:  '余军伟', seat:  '7排56号'},
  {name: '意尔康股份有限公司', person:  '李裕辉', seat:  '7排57号'},
  {name: '浙江三辰电器股份有限公司', person:  '王炳林', seat:  '7排58号'},
  {name: '绿水股份有限公司', person:  '周凌峰', seat:  '7排59号'},
  {name: '浙江青山钢铁有限公司', person:  '季灯平', seat:  '7排60号'},
  {name: '浙江越影科技有限公司', person:  '苗长龙', seat:  '7排61号'},
  {name: '钢一控股集团有限公司', person:  '季灯平', seat:  '7排62号'},
  {name: '浙江汉特姆阀门有限公司', person:  '李叶朗', seat:  '7排63号'},
  {name: '青田新机电器有限公司', person:  '翁迪院', seat:  '7排64号'},
  {name: '丽水华富大数据管理有限公司', person:  '褚升阳', seat:  '8排45号'},
  {name: '青田中科植物科技有限公司', person:  '朱伯荣', seat:  '8排46号'},
  {name: '浙江多迪斯泰保健器材有限公司', person:  '毛忠武', seat:  '8排47号'},
  {name: '安特仪表集团有限公司', person:  '袁耀祖', seat:  '8排48号'},
  {name: '青田球豹阀门配件有限公司', person:  '金燕', seat:  '8排49号'},
  {name: '浙江和信玩具集团有限公司', person:  '', seat:  '8排50号'},
  {name: '云和金成木业有限公司', person:  '', seat:  '8排51号'},
  {name: '浙江兴昌轴承有限公司', person:  '', seat:  '8排52号'},
  {name: '浙江欧菲石油设备有限公司', person:  '', seat:  '8排53号'},
  {name: '浙江汉威阀门制造有限公司', person:  '', seat:  '8排54号'},
  {name: '环驰云和钢球有限公司', person:  '', seat:  '8排55号'},
  {name: '庆元菇香食品有限公司', person:  '范华飞', seat:  '8排56号'},
  {name: '浙江瑞庆汽车零部件有限公司', person:  '周玉玲', seat:  '8排57号'},
  {name: '浙江瑞翔机电科技股份有限公司', person:  '李远财', seat:  '8排58号'},
  {name: '浙江三箭工贸有限公司', person:  '季志伟', seat:  '8排59号'},
  {name: '浙江方格药业有限公司', person:  '刘世柱', seat:  '8排60号'},
  {name: '庆元县绿尔佳食品有限公司', person:  '毛英洁', seat:  '8排61号'},
  {name: '浙江鸿星文具有限公司', person:  '郑正华', seat:  '8排62号'},
  {name: '晨龙集团有限责任公司', person:  '吕普龙', seat:  '9排45号'},
  {name: '浙江锯力煌锯床股份有限公司', person:  '李斌胜', seat:  '9排46号'},
  {name: '浙江畅尔智能装备股份有限公司', person:  '林绿高', seat:  '9排47号'},
  {name: '浙江金棒运动器材有限公司', person:  '徐勇强', seat:  '9排48号'},
  {name: '浙江华洋赛车股份有限公司', person:  '李  娅', seat:  '9排49号'},
  {name: '浙江晨雕机械有限公司', person:  '卢建飞', seat:  '9排50号'},
  {name: '浙江固驰电子有限公司', person:  '范  涛', seat:  '9排51号'},
  {name: '浙江天喜厨电股份有限公司', person:  '袁　军', seat:  '9排52号'},
  {name: '浙江金马逊机械有限公司', person:  '林伟明', seat:  '9排53号'},
  {name: '浙江涛涛车业股份有限公司', person:  '朱红霞', seat:  '9排54号'},
  {name: '浙江正达模具有限公司', person:  '吕  榕', seat:  '9排55号'},
  {name: '浙江晨龙锯床股份有限公司', person:  '丁泽林', seat:  '9排56号'},
  {name: '浙江汉达机械有限公司', person:  '应志达', seat:  '9排57号'},
  {name: '浙江省恒强针车实业有限公司', person:  '应迨吉', seat:  '9排58号'},
  {name: '浙江利民控股股份有限公司', person:  '李峰', seat:  '9排59号'},
  {name: '浙江凯恩电池有限公司', person:  '金哲宇', seat:  '9排60号'},
  {name: '浙江凯恩特种材料股份有限公司', person:  '华一鸣', seat:  '9排61号'},
  {name: '浙江赶街电子商务有限公司', person:  '邹建才', seat:  '9排62号'},
  {name: '菲立化学工程（遂昌）有限公司', person:  '俞梦龙', seat:  '9排63号'},
  {name: '浙江永上特材有限公司', person:  '鲍云飞', seat:  '9排64号'},
  {name: '浙江恒大导轨型材科技有限公司', person:  '朱会霖', seat:  '10排45号'},
  {name: '浙江遂金特种铸造有限公司', person:  '胡锡林', seat:  '10排46号'},
  {name: '浙江池河科技有限公司', person:  '李春萍', seat:  '10排47号'},
  {name: '浙江微通催化新材料有限公司', person:  '陈伟方', seat:  '10排48号'},
  {name: '浙江遂昌汇金有色金属有限公司', person:  '赵樟财', seat:  '10排49号'},
  {name: '浙江荣凯科技发展有限公司', person:  '孙鑫', seat:  '10排50号'},
  {name: '浙江华威门业有限公司', person:  '高丰', seat:  '10排51号'},
  {name: '浙江科马摩擦材料股份有限公司', person:  '王宗和', seat:  '10排52号'},
  {name: '上上德盛集团股份有限公司', person:  '芮鑫', seat:  '10排53号'},
  {name: '丽水一山绿色实业有限公司', person:  '苏承波', seat:  '10排54号'},
  {name: '景宁宇海幼教装备有限公司', person:  '李梅影', seat:  '10排55号'},
  {name: '浙江创岳金属材料有限公司', person:  '陈卫光', seat:  '10排56号'},
  {name: '浙江沈氏省心物流科技有限公司', person:  '汤信琴', seat:  '10排57号'},
  {name: '浙江康润新材料有限公司', person:  '薛奇', seat:  '10排58号'},
  {name: '景宁美乐幼教用品有限公司', person:  '李文杰', seat:  '10排59号'},
  {name: '浙江青风制冷设备制造有限公司', person:  '方云杰', seat:  '10排60号'},
  {name: '浙江景宁瓯江胶囊有限公司', person:  '何东', seat:  '10排61号'},
  {name: '浙江珏芯微电子有限公司', person:  '杨涛', seat:  '11排45号'},
  {name: '丽水中科半导体材料研究中心有限公司', person:  '艾玉杰', seat:  '11排46号'},
  {name: '浙江华润三九众益制药有限公司', person:  '潘 革', seat:  '11排47号'},
  {name: '浙江闽锋化学有限公司', person:  '叶青松', seat:  '11排48号'},
  {name: '浙江中广电器股份有限公司', person:  '朱建芬', seat:  '11排49号'},
  {name: '浙江嘉利(丽水)工业股份有限公司', person:  '漆爱冬', seat:  '11排50号'},
  {name: '浙江阿佩克斯能源科技有限公司', person:  '陈再华', seat:  '11排51号'},
  {name: '丽水绿氟科技有限公司', person:  '卢寿福', seat:  '11排52号'},
  {name: '浙江贝尼菲特药业有限公司', person:  '吴丽华', seat:  '11排53号'},
  {name: '浙江晶睿电子科技有限公司', person:  '张峰', seat:  '11排54号'},
  {name: '丽水市杰祥科技有限公司', person:  '黄祖祥', seat:  '11排55号'},
  {name: '浙江洛威尼智能雕刻机有限公司', person:  '曹琴勇', seat:  '11排56号'},
  {name: '中国高科技产业化研究会特聘副理事长', person:  '李锡涛', seat:  '11排57号'},
  {name: '', person:  '胡文君', seat:  '3排6座'},
  {name: '', person:  '曾钰峰', seat:  '3排7座'},
  {name: '', person:  '覃麟清', seat:  '3排8座'},
  {name: '', person:  '姚倩蕾', seat:  '3排9座'},
  {name: '', person:  '李政', seat:  '3排10座'},
  {name: '', person:  '严见璋', seat:  '3排11座'},
  {name: '', person:  '李元元', seat:  '3排12座'},
  {name: '', person:  '卜京伟', seat:  '3排13座'},
  {name: '', person:  '娄景辉', seat:  '3排14座'},
  {name: '', person:  '肖金华', seat:  '3排45座'},
  {name: '', person:  '范力洁', seat:  '4排6座'},
  {name: '', person:  '陈增辉', seat:  '4排7座'},
  {name: '', person:  '陈晓蕾', seat:  '4排8座'},
  {name: '', person:  '黄泽民', seat:  '4排9座'},
  {name: '', person:  '王焰', seat:  '4排10座'},
  {name: '', person:  '拜喆喆', seat:  '4排11座'},
  {name: '', person:  '郭冰', seat:  '4排12座'},
  {name: '', person:  '彭辉', seat:  '4排13座'},
  {name: '', person:  '智强', seat:  '4排14座'},
  {name: '', person:  '曲轶龙', seat:  '4排45座'},
  {name: '', person:  '于笑潇', seat:  '4排46座'},
  {name: '', person:  '吴毓琦', seat:  '5排6座'},
  {name: '', person:  '董盈', seat:  '5排7座'},
  {name: '', person:  '李嘉清', seat:  '5排8座'},
  {name: '', person:  '安昱东', seat:  '5排9座'},
  {name: '', person:  '田岱灵', seat:  '5排10座'},
  {name: '', person:  '方旖宁', seat:  '5排11座'},
  {name: '', person:  '黄薇娜', seat:  '5排12座'},
  {name: '', person:  '陈莹', seat:  '5排13座'},
  {name: '', person:  '王震', seat:  '5排14座'},
  {name: '', person:  '杨斌', seat:  '5排45座'},
  {name: '', person:  '刘进长', seat:  '5排46座'},
  {name: '', person:  '黄志平', seat:  '5排47座'},
  {name: '', person:  '沈国臻', seat:  '5排48座'},
  {name: '', person:  '刘洁', seat:  '5排49座'},
  {name: '', person:  '秦胜营', seat:  '5排50座'},
  {name: '', person:  '李兴旺', seat:  '5排51座'},
  {name: '', person:  '陈乃科', seat:  '6排45座'},
  {name: '', person:  '何晓娟', seat:  '6排46座'},
  {name: '', person:  '曹琴勇', seat:  '6排47座'},
  {name: '', person:  '叶海杰', seat:  '6排48座'},
  {name: '', person:  '郑建世', seat:  '6排49座'},
  {name: '', person:  '叶庆盛', seat:  '6排50座'},
  {name: '', person:  '叶先平', seat:  '6排51座'},
  {name: '', person:  '吕 侃', seat:  '6排52座'},
  {name: '', person:  '李丰', seat:  '6排53座'},
  {name: '', person:  '詹旭彬', seat:  '6排54座'},
  {name: '', person:  '章丽英', seat:  '6排55座'},
  {name: '', person:  '季永灵', seat:  '6排56座'},
  {name: '', person:  '张江欧', seat:  '6排57座'},
  {name: '', person:  '叶伟', seat:  '6排58座'},
  {name: '', person:  '马国进', seat:  '6排59座'},
  {name: '', person:  '金涛', seat:  '6排60座'},
  {name: '', person:  '陈云', seat:  '6排61座'},
  {name: '', person:  '李虎', seat:  '6排62座'},
  {name: '', person:  '程行坤', seat:  '6排63座'},
  {name: '', person:  '王洋', seat:  '6排64座'},
  {name: '', person:  '宋晶晶', seat:  '6排65座'},
  {name: '', person:  '陈豪', seat:  '3排46座'},
  {name: '', person:  '吴郁郁', seat:  '3排47座'},
  {name: '', person:  '王平', seat:  '3排48座'},
  {name: '', person:  '吴松平', seat:  '3排49座'},
  {name: '', person:  '吴绍长', seat:  '3排50座'},
  {name: '', person:  '邱伟文', seat:  '3排51座'},
  {name: '', person:  '蒋黎红', seat:  '3排52座'},
  {name: '', person:  '曹世亮', seat:  '3排53座'},
  {name: '', person:  '陈维杰', seat:  '3排54座'},
  {name: '', person:  '陈庚', seat:  '3排55座'},
  {name: '', person:  '刘晓峰', seat:  '3排56座'},
  {name: '', person:  '夏侯辉', seat:  '3排57座'},
  {name: '', person:  '王文勇', seat:  '3排58座'},
  {name: '', person:  '柏友周', seat:  '3排59座'},
  {name: '', person:  '叶品勇', seat:  '3排60座'},
  {name: '', person:  '叶芳', seat:  '3排61座'},
  {name: '', person:  '徐凌', seat:  '3排62座'},
  {name: '', person:  '曾庆', seat:  '3排63座'},
  {name: '', person:  '纪建松', seat:  '3排64座'},
  {name: '', person:  '张俊', seat:  '4排47座'},
  {name: '', person:  '蔡成岗', seat:  '4排48座'},
  {name: '', person:  '唐艳军', seat:  '4排49座'},
  {name: '', person:  '傅顺开', seat:  '4排50座'},
  {name: '', person:  '刘洪海', seat:  '4排51座'},
  {name: '', person:  '吴良专', seat:  '4排52座'},
  {name: '', person:  '祝涛', seat:  '4排53座'},
  {name: '', person:  '苗长龙', seat:  '4排54座'},
  {name: '', person:  '张根', seat:  '4排55座'},
  {name: '', person:  '杨光', seat:  '4排56座'},
  {name: '', person:  '林群书', seat:  '4排57座'},
  {name: '', person:  '王挺', seat:  '4排58座'},
  {name: '', person:  '魏乃绪', seat:  '4排59座'},
  {name: '', person:  '吴伟伟', seat:  '4排60座'},
  {name: '', person:  '李喆', seat:  '4排61座'},
  {name: '', person:  '胡创悦', seat:  '4排62座'},
  {name: '', person:  '林娟', seat:  '4排63座'},
  {name: '', person:  '张维加', seat:  '4排64座'},
  {name: '', person:  '范芳芳', seat:  '5排52座'},
  {name: '', person:  '郭江', seat:  '5排53座'},
  {name: '', person:  '谢正林', seat:  '5排54座'},
  {name: '', person:  '徐松琳', seat:  '5排55座'},
  {name: '', person:  '陈世维', seat:  '5排56座'},
  {name: '', person:  '步月宾', seat:  '5排57座'},
  {name: '', person:  '张旭超', seat:  '5排58座'},
  {name: '', person:  '吴一江', seat:  '5排59座'},
  {name: '', person:  '李昊轩', seat:  '5排60座'},
  {name: '', person:  '张峰', seat:  '5排61座'},
  {name: '', person:  '陈恳', seat:  '5排62座'},
  {name: '', person:  '吕雪峰', seat:  '5排63座'},
  {name: '', person:  '胡国军', seat:  '6排3座'},
  {name: '', person:  '王旭', seat:  '6排1座'},
  {name: '', person:  '孙学锋', seat:  '6排6座'},
  {name: '', person:  '范九洋', seat:  '6排4座'},
  {name: '', person:  '贺光', seat:  '4排5座'},
  {name: '', person:  '何  珏', seat:  '4排4座'},
  {name: '', person:  ' 夏景林', seat:  '4排3座'},
  {name: '', person:  '许冬武', seat:  '4排2座'},
  {name: '', person:  '梁韶晖', seat:  '4排1座'},
  {name: '', person:  ' 燕  振', seat:  '5排5座'},
  {name: '', person:  '夏凯愉', seat:  '5排4座'},
  {name: '', person:  '周玲玲 ', seat:  '5排2座'},
  {name: '', person:  '俞根君', seat:  '5排3座'},
  {name: '', person:  '鲍  蓉', seat:  '5排1座'},
  {name: '', person:  '李如涛', seat:  '3排21座'},
  {name: '', person:  '田晓萍', seat:  '3排20座'},
  {name: '', person:  '俞熙娜', seat:  '3排19座'},
  {name: '', person:  '林男', seat:  '3排18座'},
  {name: '', person:  '丁元胜', seat:  '3排17座'},
  {name: '', person:  '卢鹏程', seat:  '3排16座'},
  {name: '', person:  '徐新清', seat:  '3排15座'},
  {name: '', person:  '任思怡 ', seat:  '4排21座'},
  {name: '', person:  '朱丹阳', seat:  '4排20座'},
  {name: '', person:  '柴鸿', seat:  '4排19座'},
  {name: '', person:  '杨建平  ', seat:  '4排18座'},
  {name: '', person:  '郑炜哲 ', seat:  '4排17座'},
  {name: '', person:  '李俊鹏', seat:  '4排16座'},
  {name: '', person:  '刘云', seat:  '4排15座'},
  {name: '', person:  '王志罡', seat:  '6排14座'},
  {name: '', person:  '孔维娜', seat:  '6排13座'},
  {name: '', person:  '卢寿福', seat:  '6排12座'},
  {name: '', person:  '郭胜华', seat:  '6排11座'},
  {name: '', person:  '陈勇华', seat:  '6排10座'},
  {name: '', person:  '邹建兵', seat:  '6排9座'},
  {name: '', person:  '傅旭敏', seat:  '6排8座'},
  {name: '', person:  '叶志一', seat:  '6排7座'},
  {name: '', person:  '范浩军', seat:  '5排21座'},
  {name: '', person:  '陈治军', seat:  '5排20座'},
  {name: '', person:  '钟世龙', seat:  '5排19座'},
  {name: '', person:  '任国强', seat:  '5排18座'},
  {name: '', person:  '苏小虎', seat:  '5排17座'},
  {name: '', person:  '翟慎强', seat:  '5排16座'},
  {name: '', person:  '马晓宇', seat:  '5排15座'},
  {name: '', person:  '郭清', seat:  '6排21座'},
  {name: '', person:  '刘宏', seat:  '6排20座'},
  {name: '', person:  '杨涛', seat:  '6排19座'},
  {name: '', person:  '杨晓光', seat:  '6排18座'},
  {name: '', person:  '陶宁', seat:  '6排17座'},
  {name: '', person:  '樊建秋', seat:  '6排16座'},
  {name: '', person:  '薛龙', seat:  '6排15座'},
  {name: '', person:  '李桂鹏', seat:  '3排3座'},
  {name: '', person:  '沈世山', seat:  '7排33座'},
  {name: '', person:  '饶鸿来', seat:  '7排32座'},
  {name: '', person:  '郑利剑', seat:  '7排34座'},
  {name: '', person:  '柳向阳', seat:  '7排31座'},
  {name: '', person:  '吴松平', seat:  '3排48座'},
  {name: '', person:  '叶伯军', seat:  '3排33座'},
  {name: '', person:  '李一波', seat:  '3排32座'},
  {name: '', person:  '李汉勤', seat:  '3排34座'},
  {name: '', person:  '陈  豪', seat:  '3排45座'},
  {name: '', person:  '胡献如', seat:  '3排31座'},
  {name: '', person:  '胡 刚', seat:  '3排35座'},
  {name: '', person:  '刘云华', seat:  '7排35座'},
  {name: '', person:  '李世超', seat:  '3排23座'},
  {name: '', person:  '叶建利', seat:  '7排30座'},
  {name: '', person:  '　邱文锋', seat:  '7排36座'},
  {name: '', person:  '　陈志斌', seat:  '7排29座'},
  {name: '', person:  '蔡培新', seat:  '7排37座'},
  {name: '', person:  '王奕', seat:  '7排28座'},
  {name: '', person:  '邱旭平', seat:  '7排38座'},
  {name: '', person:  '卢汝兰', seat:  '7排27座'},
  {name: '', person:  '陈科强', seat:  '3排44座'},
  {name: '', person:  '尚勇庆', seat:  '7排39座'},
  {name: '', person:  '潘晓泉', seat:  '7排26座'},
  {name: '', person:  '吴守成', seat:  '7排40座'},
  {name: '', person:  '任韩高', seat:  '7排25座'},
  {name: '', person:  '张卫英', seat:  '7排41座'},
  {name: '', person:  '蓝海', seat:  '7排24座'},
  {name: '', person:  '王炜', seat:  '7排42座'},
  {name: '', person:  '郑绍周', seat:  '7排23座'},
  {name: '', person:  '王国锋', seat:  '7排43座'},
  {name: '', person:  '　廖宝云', seat:  '7排22座'},
  {name: '', person:  '雷华英', seat:  '7排44座'},
  {name: '', person:  '周显荣', seat:  '8排33座'},
  {name: '', person:  '　翁伟荣', seat:  '8排32座'},
  {name: '', person:  '　王平', seat:  '3排47座'},
  {name: '', person:  '蔡昉', seat:  '8排34座'},
  {name: '', person:  '丁文伟', seat:  '8排31座'},
  {name: '', person:  '胡汉彪', seat:  '8排35座'},
  {name: '', person:  '叶水源', seat:  '8排30座'},
  {name: '', person:  '蒋世懿', seat:  '8排36座'},
  {name: '', person:  '潘建青', seat:  '8排29座'},
  {name: '', person:  '邢志行', seat:  '8排37座'},
  {name: '', person:  '雷金松', seat:  '8排28座'},
  {name: '', person:  '叶旭勇', seat:  '8排38座'},
  {name: '', person:  '林宇清', seat:  '8排27座'},
  {name: '', person:  '孙俐珑', seat:  '8排39座'},
  {name: '', person:  '陈子民', seat:  '8排26座'},
  {name: '', person:  '吴郁郁', seat:  '3排46座'},
  {name: '', person:  '蒋正鸿', seat:  '8排40座'},
  {name: '', person:  '王世强', seat:  '8排25座'},
  {name: '', person:  '　邹向阳', seat:  '8排41座'},
  {name: '', person:  '　刘崇民', seat:  '8排24座'},
  {name: '', person:  '杨雷', seat:  '8排42座'},
  {name: '', person:  '夏海国', seat:  '8排23座'},
  {name: '', person:  '陆亚东', seat:  '8排43座'},
  {name: '', person:  '周智飞', seat:  '8排22座'},
  {name: '', person:  '　詹百松', seat:  '8排44座'},
  {name: '', person:  '周光洪', seat:  '9排33座'},
  {name: '', person:  '　陈建广', seat:  '9排32座'},
  {name: '', person:  '柳启东', seat:  '9排34座'},
  {name: '', person:  '徐荷生', seat:  '9排31座'},
  {name: '', person:  '李志伟', seat:  '9排35座'},
  {name: '', person:  '徐青清', seat:  '9排30座'},
  {name: '', person:  '应勇军', seat:  '9排36座'},
  {name: '', person:  '　张妍', seat:  '9排29座'},
  {name: '', person:  '管伟春', seat:  '9排37座'},
  {name: '', person:  '程定飞', seat:  '9排28座'},
  {name: '', person:  '　潘志强', seat:  '9排38座'},
  {name: '', person:  '郭海光', seat:  '9排27座'},
  {name: '', person:  '　蔡通友', seat:  '9排39座'},
  {name: '', person:  '　王提操', seat:  '9排26座'},
  {name: '', person:  '王栋', seat:  '9排40座'},
  {name: '', person:  '廖永平', seat:  '9排25座'},
  {name: '', person:  '胡慧红', seat:  '9排41座'},
  {name: '', person:  '江少伟', seat:  '9排24座'},
  {name: '', person:  '　吴盛华', seat:  '9排42座'},
  {name: '', person:  '黄金明', seat:  '9排23座'},
  {name: '', person:  '罗叶中', seat:  '9排43座'},
  {name: '', person:  '褚志坚', seat:  '9排22座'},
  {name: '', person:  '胡锋吉', seat:  '9排44座'},
  {name: '', person:  '王军', seat:  '10排33座'},
  {name: '', person:  '黄刚', seat:  '10排32座'},
  {name: '', person:  '邹新花', seat:  '10排34座'},
  {name: '', person:  '叶郑献', seat:  '10排31座'},
  {name: '', person:  '叶茂', seat:  '10排35座'},
  {name: '', person:  '李纪灵', seat:  '10排30座'},
  {name: '', person:  '　阮建明', seat:  '10排36座'},
  {name: '', person:  '钱敏', seat:  '10排29座'},
  {name: '', person:  '郑建飞', seat:  '10排37座'},
  {name: '', person:  '沈伏恒', seat:  '10排28座'},
  {name: '', person:  '何炯伟', seat:  '10排38座'},
  {name: '', person:  '　王卫青', seat:  '10排27座'},
  {name: '', person:  '洪勇华', seat:  '10排39座'},
  {name: '', person:  '林远', seat:  '10排26座'},
  {name: '', person:  '吴小华', seat:  '10排40座'},
  {name: '', person:  '金仁樟', seat:  '10排25座'},
  {name: '', person:  '许文醉', seat:  '10排41座'},
  {name: '', person:  '蓝叶培', seat:  '10排24座'},
  {name: '', person:  '　范寿仁', seat:  '10排42座'},
  {name: '', person:  '陈仕恩', seat:  '10排23座'},
  {name: '', person:  '李立金', seat:  '10排43座'},
  {name: '', person:  '　虞小阳', seat:  '10排22座'},
  {name: '', person:  '胡大杭', seat:  '10排44座'},
  {name: '', person:  '留丽萍', seat:  '11排34座'},
  {name: '', person:  '项武', seat:  '11排31座'},
  {name: '', person:  '　季巧英', seat:  '11排35座'},
  {name: '', person:  '　吴绍长', seat:  '3排49座'},
  {name: '', person:  '　郑武积', seat:  '11排30座'},
  {name: '', person:  '朱伟强', seat:  '11排36座'},
  {name: '', person:  '　许碎平', seat:  '11排29座'},
  {name: '', person:  '章旭', seat:  '6排5座'},
  {name: '', person:  '　吕志充', seat:  '11排28座'},
  {name: '', person:  '金丽芬', seat:  '11排37座'},
  {name: '', person:  '陈杰', seat:  '11排27座'},
  {name: '', person:  '叶绍飞', seat:  '11排38座'},
  {name: '', person:  '杜永明', seat:  '11排26座'},
  {name: '', person:  '叶荣林', seat:  '11排39座'},
  {name: '', person:  '吕安', seat:  '11排25座'},
  {name: '', person:  '毛时薛', seat:  '11排40座'},
  {name: '', person:  '程浙军', seat:  '3排1座'},
  {name: '', person:  '徐瑛', seat:  '6排2座'},
  {name: '', person:  '蓝先芬', seat:  '11排41座'},
  {name: '', person:  '邱伟平', seat:  '11排24座'},
  {name: '', person:  '陈美芬', seat:  '11排42座'},
  {name: '', person:  '邱伟文', seat:  '3排50座'},
  {name: '', person:  '廖正青', seat:  '11排23座'},
  {name: '', person:  '刘欣', seat:  '11排43座'},
  {name: '', person:  '　翁跃平', seat:  '12排33座'},
  {name: '', person:  '林青', seat:  '12排32座'},
  {name: '', person:  '　郑忠勇', seat:  '12排34座'},
  {name: '', person:  '叶海波', seat:  '12排31座'},
  {name: '', person:  '　江诗仁', seat:  '12排35座'},
  {name: '', person:  '黄丽萍', seat:  '12排30座'},
  {name: '', person:  '　雷强', seat:  '12排36座'},
  {name: '', person:  '吴小波', seat:  '12排29座'},
  {name: '', person:  '　胡荣炎', seat:  '12排37座'},
  {name: '', person:  '黄伟君', seat:  '12排28座'},
  {name: '', person:  '张林', seat:  '12排38座'},
  {name: '', person:  '叶世伟', seat:  '12排27座'},
  {name: '', person:  '赵龙友', seat:  '12排39座'},
  {name: '', person:  '　姜丽云', seat:  '12排26座'},
  {name: '', person:  '王赳', seat:  '12排40座'},
  {name: '', person:  '吕回', seat:  '12排25座'},
  {name: '', person:  '鲍倩倩', seat:  '12排41座'},
  {name: '', person:  '潘晓伟', seat:  '12排24座'},
  {name: '', person:  '孔靖雯', seat:  '12排42座'},
  {name: '', person:  '陈永超', seat:  '9排21座'},
  {name: '', person:  '叶庆武', seat:  '10排21座'},
  {name: '', person:  '张  濂', seat:  '11排21座'},
  {name: '', person:  '雷超', seat:  '9排20座'},
  {name: '', person:  '叶亚东', seat:  '10排20座'},
  {name: '', person:  '徐一桂', seat:  '11排20座'},
  {name: '', person:  '金志红', seat:  '9排19座'},
  {name: '', person:  '童森军', seat:  '9排13座'},
  {name: '', person:  '章旭阳', seat:  '10排19座'},
  {name: '', person:  '叶永青', seat:  '11排19座'},
  {name: '', person:  '黄伟杰', seat:  '9排18座'},
  {name: '', person:  '官军军', seat:  '10排18座'},
  {name: '', person:  '王燕萍', seat:  '11排18座'},
  {name: '', person:  '刘新民', seat:  '9排17座'},
  {name: '', person:  '吴永林', seat:  '10排17座'},
  {name: '', person:  '吴宗元', seat:  '11排17座'},
  {name: '', person:  '刘洁阳', seat:  '9排16座'},
  {name: '', person:  '项振平', seat:  '10排16座'},
  {name: '', person:  '洪耀', seat:  '11排16座'},
  {name: '', person:  '顾奕滨', seat:  '9排15座'},
  {name: '', person:  '杨捷', seat:  '10排15座'},
  {name: '', person:  '徐玮珺', seat:  '11排15座'},
  {name: '', person:  '雷剑锋', seat:  '9排14座'},
  {name: '', person:  '何开健', seat:  '10排14座'},
  {name: '', person:  '叶辉华', seat:  '11排14座'},
  {name: '', person:  '马盈', seat:  '9排12座'},
  {name: '', person:  '徐卫斌', seat:  '10排13座'},
  {name: '', person:  '刘健', seat:  '11排13座'},
  {name: '', person:  '蓝金水', seat:  '11排33座'},
  {name: '', person:  '李舜', seat:  '11排32座'},
  ]